# Introduction

#####         Numpy is the fundamental package for scientific computing in python.It is a python library that provides a multidimensional array object, various derived objects( e.g. masked array and matrices). It is best suitable for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete, basic linear algebra operations etc.

 The core part of Numpy package is **ndarray** object. This encapsulates n-dimensional array of homogeneous data types, with many operations being performed in the compiled code for performance

### Difference Between Python Standard Sequences and Numpy Arrays

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original
* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically,such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences

### Why is NumPy Fast?

There are two most powerful numpy's feature:- Vectorization and Broadcasting

**Vectorization:-** 
            Vectorization describes absense of any explicit looping, indexing etc in the code, these things are taking place **behind the scenes** in optimized, pre-compiled C code. 

Advantages of vectorization:-
* Vectorized code is more concise and easier to read
* Fewer lines of code generally means fewer bugs 

**Broadcasting:-** Broadcasting is the term used to describe the implicit element-by-element behaviour of operations

### The Basics

   Numpy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.
* Ex 1. Co-ordinates of a point in 3D space [1,2,3] is axes 1
* Ex 2. [[1.,0.0.], [0.,1.,2.]] has axes 2

Numpy's array class is ***ndarray***. important attributes of ndarray object are:-
* **ndarray.ndim:-**  the number of axes (dimensions) of the array.
* **ndarray.shape:-** the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
* **ndarray.size:-** the total number of elements of the array. This is equal to the product of the elements of shape.
* **ndarray.dtype:-** An object describing the type of the elements in the array.
* **ndarray.data:-** The buffer containing the actual elements of the array.

### Example:- 


In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [10]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [11]:
type(b)

numpy.ndarray

## Array Creation

Through python standard sequences

In [12]:
l=[1,2,34,6]
a=np.array(l)
a

array([ 1,  2, 34,  6])

In [13]:
a.dtype

dtype('int32')

In [15]:
b=np.array([1.2,34.5,78])
b.dtype

dtype('float64')

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into threedimensional
arrays, and so on.

In [17]:
b=np.array([(3,4,5),(0,9,4)])
b

array([[3, 4, 5],
       [0, 9, 4]])

The type of array can be explicitly specified at the creation time.

In [18]:
c=np.array([[1,2],[6,7]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [6.+0.j, 7.+0.j]])

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory

In [20]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((2,1,4),dtype='int64')  # 2 rows while each row containing 1x4 array

array([[[1, 1, 1, 1]],

       [[1, 1, 1, 1]]], dtype=int64)

In [23]:
np.ones((3,2,4),dtype='int64')  # 3 rows while each row containing 2x4 array

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

## Adding Removing and Sorting of elements

#### np.sort(), np.concatenate()

In [24]:
arr = np.array([5,8,3,5,1,4,3,2,5,7,3])
np.sort(arr)

array([1, 2, 3, 3, 3, 4, 5, 5, 5, 7, 8])

In [26]:
a = np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
np.concatenate((x,y),axis=0) # for axis = 0 for row-wise otherwise 1 for column-wise

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
arr = np.array([[[0,1,2,3],
                [4,5,6,7]],
               [[0,1,2,3],
               [4,5,6,7]],
               [[0,1,2,3],
               [4,5,6,7]]])
print(arr.ndim) #no of axis in the array
print(arr.shape) #ndarray.shape will display a tuple of integers that indicate the number of elements
                #stored along each dimension of the array
print(arr.size) #no of elements in the array

3
(3, 2, 4)
24


## Can we reshape an array

arr.reshape() will give a new shape to an array without changing the data.Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array

In [31]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [32]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
np.reshape(a,newshape=(1,6),order='C')

array([[0, 1, 2, 3, 4, 5]])

## How to convert a 1D array into a 2D array (how to add a new axis to an array)

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

In [36]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [37]:
a.shape

(6,)

In [41]:
#We can use np.newaxis to add a new axis:
a2 = a[np.newaxis,:]
print(a2.shape)
print(a2)

(1, 6)
[[0 1 2 3 4 5]]


We can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis.
We can conver a 1D array to a row vector by inserting an axis along the first dimension

In [48]:
b = np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [44]:
row_vector = a[np.newaxis,:]
row_vector.shape

(1, 6)

In [46]:
col_vector = a[:,np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


## Indexing and Slicing 

In [49]:
data = np.array([1,2,3])
data[1]
data[0:2]

array([1, 2])

In [50]:
data[-2:]

array([2, 3])

In [52]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
print(a[a<5])

[1 2 3 4]


In [55]:
five_up = (a >= 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [60]:
c = (a>2) & (a<11)
print(c)
print(a[c])

[[False False  True  True]
 [ True  True  True  True]
 [ True  True False False]]
[ 3  4  5  6  7  8  9 10]


In [61]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [62]:
b = np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In this example, a tuple of arrays was returned: one for each dimension. The first row shows the row indices while the second row shows the column indices where the values are found.
If we want to generate a list of coordinates where the element exist, we can zip the arrays,iterate over the list of coordinates and print them.

In [64]:
list_of_coordinates = list(zip(b[0],b[1]))
for item in list_of_coordinates:
    print(item)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


### How to Create an array from existing data

np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [69]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [70]:
arr1 = a[3:8]
arr1 

array([4, 5, 6, 7, 8])

In [72]:
a1  = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])

In [74]:
#stack arrays vertically using np.vstack() method
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [77]:
#stack arrays horizontally using np.hstack() method
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

We can split an array into several smaller arrays using hsplit. We can specify the number of equally shaped arrays to return or the columns after which the division should occur.

In [83]:
x = np.arange(1,25).reshape(4,-1)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [84]:
#If I want to split this array into three equally shaped arrays
np.hsplit(x,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [85]:
#If I want to split this array into 2 equally shaped arrays
np.hsplit(x,2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

## Basic Array  Operation